FROM registry.gitlab.com/alexhaydock/dockerfiles:jekyll as builder
LABEL maintainer "Alex Haydock <alex@alexhaydock.co.uk>"

COPY . /tmp/alexhaydock.co.uk
WORKDIR /tmp/alexhaydock.co.uk
RUN bundle install
RUN bundle exec jekyll build

FROM nginx:stable-alpine
COPY --from=builder /tmp/alexhaydock.co.uk/_site /usr/share/nginx/html